from .dashboard import dashboard_layout
from .dashboard_add import dashboard_add_layout
from .dashboard_delete import dashboard_delete_layout
from .dashboard_not_connected import dashboard_not_connected_layout
from .dashboard_detail import dashboard_detail_layout